### ISSUE TITLE
Different filename convention

### ISSUE THREAD

**Issue by mfitzasp** [zemogle/astrosource#10]
The pipeline files (e.g. psx, sek, etc.) have a different naming convention since astrosource was bundled up.

Basically the exposure time [5] and the BJD [2] have been reversed. This was done so that when sorted alphanumerically, the files would be sorted in order of date for users who manually explore their files and to solve a sorting glitch using these images in astroImageJ.

This is actually a simple fix.... 1) swap exposure time and BJD in the naming convention for the csv extracted from the fz file and 2) Find the ONE location (from memory) where the filename is split to extract the BJD and change that from [5] to [2]

**Comment by zemogle** [comment]
Covered by 71ce499

Check this is what you wanted and close the issue.

**Comment by zemogle** [comment]
This should be fully covered now.
